# PopGen 1.0 is A Synthetic Population Generator for Advanced
# Microsimulation Models of Travel Demand 
# Copyright (C) 2009, Arizona State University
# See PopGen/License

DEFAULT_PERSON_PUMS_QUERIES = [ "alter table person_pums add column agep bigint",
                                "alter table person_pums add column gender bigint",
                                "alter table person_pums add column race bigint",
                                "alter table person_pums add column employment bigint",
                                "update person_pums set agep = 1 where age < 5",
                                "update person_pums set agep = 2 where age >= 5 and age < 15",
                                "update person_pums set agep = 3 where age >= 15 and age < 25",
                                "update person_pums set agep = 4 where age >= 25 and age < 35",
                                "update person_pums set agep = 5 where age >= 35 and age < 45",
                                "update person_pums set agep = 6 where age >= 45 and age < 55",
                                "update person_pums set agep = 7 where age >= 55 and age < 65",
                                "update person_pums set agep = 8 where age >= 65 and age < 75",
                                "update person_pums set agep = 9 where age >= 75 and age < 85",
                                "update person_pums set agep = 10 where age >= 85",
                                "update person_pums set gender = sex",
                                "update person_pums set race = 1 where race1 = 1",
                                "update person_pums set race = 2 where race1 = 2",
                                "update person_pums set race = 3 where race1 >=3 and race1 <= 5",
                                "update person_pums set race = 4 where race1 = 6",
                                "update person_pums set race = 5 where race1 = 7",
                                "update person_pums set race = 6 where race1 = 8",
                                "update person_pums set race = 7 where race1 = 9",
                                "update person_pums set employment = 1 where esr = 0",
                                "update person_pums set employment = 2 where esr = 1 or esr = 2 or esr = 4 or esr = 5",
                                "update person_pums set employment = 3 where esr = 3",
                                "update person_pums set employment = 4 where esr = 6",
                                "drop table person_sample",
                                "create table person_sample select state, pumano, hhid, serialno, pnum, pweight, agep, gender, race, employment, relate from person_pums",
                                "alter table person_sample add index(serialno, pnum)",
                                "drop table hhld_sample_temp",
                                "alter table hhld_sample drop column agep",
                                "alter table hhld_sample rename to hhld_sample_temp",
                                "drop table hhld_sample",
                                "create table hhld_sample select hhld_sample_temp.*, agep from hhld_sample_temp left join person_sample using(serialno) where relate = 1",
                                "update hhld_sample set agep = 1 where agep <=7 ",
                                "update hhld_sample set agep = 2 where agep >7"]


DEFAULT_HOUSING_PUMS_QUERIES = ["alter table housing_pums add index(serialno)",
                                "alter table housing_pums add column hhtype bigint",
                                "alter table housing_pums add column hhldtype bigint",
                                "alter table housing_pums add column hhldinc bigint",
                                "alter table housing_pums add column hhldtenure bigint",
                                "alter table housing_pums add column hhldsize bigint",
                                "alter table housing_pums add column childpresence bigint",
                                "alter table housing_pums add column groupquarter bigint",
                                "alter table housing_pums add column hhldfam bigint",
                        
                                "update housing_pums set hhtype = 1 where unittype = 0",
                                "update housing_pums set hhtype = 2 where unittype = 1 or unittype = 2",
                                "update housing_pums set hhldtype = 1 where hht = 1",
                                "update housing_pums set hhldtype = 2 where hht = 2",
                                "update housing_pums set hhldtype = 3 where hht = 3",
                                "update housing_pums set hhldtype = 4 where hht = 4 or hht = 5",
                                "update housing_pums set hhldtype = 5 where hht = 6 or hht = 7",
                                "update housing_pums set hhldtype = -99 where hht = 0",
                                "update housing_pums set hhldinc = 1 where hinc <15000",
                                "update housing_pums set hhldinc = 2 where hinc >= 15000 and hinc < 25000",
                                "update housing_pums set hhldinc = 3 where hinc >= 25000 and hinc < 35000",
                                "update housing_pums set hhldinc = 4 where hinc >= 35000 and hinc < 45000",
                                "update housing_pums set hhldinc = 5 where hinc >= 45000 and hinc < 60000",
                                "update housing_pums set hhldinc = 6 where hinc >= 60000 and hinc < 100000",
                                "update housing_pums set hhldinc = 7 where hinc >= 100000 and hinc < 150000",
                                "update housing_pums set hhldinc = 8 where hinc >= 150000",
                                "update housing_pums set hhldinc = -99 where hht = 0",                          
                                #"update housing_pums set hhldtenure = 1 where tenure = 1 or tenure = 2",
                                #"update housing_pums set hhldtenure = 2 where tenure = 3 or tenure = 4",
                                #"update housing_pums set hhldtenure = -99 where tenure = 0",                          
                                "update housing_pums set hhldsize = persons where persons < 7",
                                "update housing_pums set hhldsize = 7 where persons >= 7",
                                "update housing_pums set hhldsize = -99 where hht = 0",                          
                                "update housing_pums set childpresence = 1 where noc > 0",
                                "update housing_pums set childpresence = 2 where noc = 0",
                                "update housing_pums set childpresence = -99 where hht = 0",                          
                                "update housing_pums set groupquarter = unittype where unittype >0",
                                "update housing_pums set groupquarter = -99 where unittype =0",
                                
                                "update housing_pums set hhldfam = 1 where hhldtype <=3",
                                "update housing_pums set hhldfam = 2 where hhldtype > 3",

                                "delete from housing_pums where persons = 0",
                                "drop table hhld_sample",
                                "drop table gq_sample",
                                "create table hhld_sample select state, pumano, hhid, serialno, hhtype, hhldtype, hhldinc, hhldsize, childpresence, hhldfam from housing_pums where hhtype = 1",
                                "create table gq_sample select state, pumano, hhid, serialno, hhtype, groupquarter from housing_pums where hhtype = 2",
                                "alter table hhld_sample add index(serialno)",
                                "alter table gq_sample add index(serialno)"]


DEFAULT_SF_QUERIES = ["alter table %s add column agep1 bigint",
                      "alter table %s add column agep2 bigint",
                      "alter table %s add column agep3 bigint",
                      "alter table %s add column agep4 bigint",
                      "alter table %s add column agep5 bigint",
                      "alter table %s add column agep6 bigint",
                      "alter table %s add column agep7 bigint",
                      "alter table %s add column agep8 bigint",
                      "alter table %s add column agep9 bigint",
                      "alter table %s add column agep10 bigint",
                      "alter table %s add column gender1 bigint",
                      "alter table %s add column gender2 bigint",
                      "alter table %s add column race1 bigint",
                      "alter table %s add column race2 bigint",
                      "alter table %s add column race3 bigint",
                      "alter table %s add column race4 bigint",
                      "alter table %s add column race5 bigint",
                      "alter table %s add column race6 bigint",
                      "alter table %s add column race7 bigint",
                      "alter table %s add column employment1 bigint",
                      "alter table %s add column employment2 bigint",
                      "alter table %s add column employment3 bigint",
                      "alter table %s add column employment4 bigint",
                      "alter table %s add column childpresence1 bigint",
                      "alter table %s add column childpresence2 bigint",
                      "alter table %s add column groupquarter1 bigint",
                      "alter table %s add column groupquarter2 bigint",
                      "alter table %s add column hhldinc1 bigint",
                      "alter table %s add column hhldinc2 bigint",
                      "alter table %s add column hhldinc3 bigint",
                      "alter table %s add column hhldinc4 bigint",
                      "alter table %s add column hhldinc5 bigint",
                      "alter table %s add column hhldinc6 bigint",
                      "alter table %s add column hhldinc7 bigint",
                      "alter table %s add column hhldinc8 bigint",
                      "alter table %s add column hhldsize1 bigint",
                      "alter table %s add column hhldsize2 bigint",
                      "alter table %s add column hhldsize3 bigint",
                      "alter table %s add column hhldsize4 bigint",
                      "alter table %s add column hhldsize5 bigint",
                      "alter table %s add column hhldsize6 bigint",
                      "alter table %s add column hhldsize7 bigint",
                      "alter table %s add column hhldtype1 bigint",
                      "alter table %s add column hhldtype2 bigint",
                      "alter table %s add column hhldtype3 bigint",
                      "alter table %s add column hhldtype4 bigint",
                      "alter table %s add column hhldtype5 bigint",
                      "alter table %s add column hhldrage1 bigint",
                      "alter table %s add column hhldrage2 bigint",
                      "alter table %s add column hhldfam1 bigint",
                      "alter table %s add column hhldfam2 bigint",
                      
                      
                      "update %s set agep1 = (P008003+P008004+P008005+P008006+P008007) + (P008042+P008043+P008044+P008045+P008046)",
                      "update %s set agep2 = (P008008+P008009+P008010+P008011+P008012+P008013+P008014+P008015+P008016+P008017 ) + (P008047+P008048+P008049+P008050+P008051+P008052+P008053+P008054+P008055+P008056)",
                      "update %s set agep3 = (P008018+P008019+P008020+P008021+P008022+P008023+P008024+P008025 ) + (P008057+P008058+P008059+P008060+P008061+P008062+P008063+P008064)",
                      "update %s set agep4 = (P008026+P008027) + (P008065+P008066)",
                      "update %s set agep5 = (P008028+P008029) + (P008067+P008068)",
                      "update %s set agep6 = (P008030+P008031) + (P008069+P008070)",
                      "update %s set agep7 = (P008032+P008033+P008034) + (P008071+P008072+P008073)",
                      "update %s set agep8 = (P008035+P008036+P008037) + (P008074+P008075+P008076)",
                      "update %s set agep9 = (P008038+P008039) + (P008077+P008078)",
                      "update %s set agep10 = (P008040) + (P008079)",
                      "update %s set gender1 = P008002", 
                      "update %s set gender2 = P008041", 
                      "update %s set race1 = P006002",
                      "update %s set race2 = P006003",
                      "update %s set race3 = P006004",
                      "update %s set race4 = P006005",
                      "update %s set race5 = P006006",
                      "update %s set race6 = P006007",
                      "update %s set race7 = P006008",
                      "update %s set employment1 = agep1+agep2+P008018+P008057",
                      "update %s set employment2 = P043004+P043006+P043011+P043013",
                      "update %s set employment3 = P043007+P043014",
                      "update %s set employment4 = P043008+P043015",
                      "update %s set childpresence1 = P010008 + P010012 + P010015",
                      "update %s set childpresence2 = P010009 + P010013 + P010016 + P010017 + P010002",
                      "update %s set groupquarter1 = P009026",
                      "update %s set groupquarter2 = P009027",
                      "update %s set hhldinc1 = P052002 + P052003",
                      "update %s set hhldinc2 = P052004 + P052005",
                      "update %s set hhldinc3 = P052006 + P052007",
                      "update %s set hhldinc4 = P052008 + P052009",
                      "update %s set hhldinc5 = P052010 + P052011",
                      "update %s set hhldinc6 = P052012 + P052013",
                      "update %s set hhldinc7 = P052014 + P052015",
                      "update %s set hhldinc8 = P052016 + P052017",
                      "update %s set hhldsize1 = P014010 ",
                      "update %s set hhldsize2 = P014003+P014011 ",
                      "update %s set hhldsize3 = P014004+P014012 ",
                      "update %s set hhldsize4 = P014005+P014013 ",
                      "update %s set hhldsize5 = P014006+P014014 ",
                      "update %s set hhldsize6 = P014007+P014015 ",
                      "update %s set hhldsize7 = P014008+P014016 ",
                      "update %s set hhldtype1 = P010007",
                      "update %s set hhldtype2 = P010011 ",
                      "update %s set hhldtype3 = P010014",
                      "update %s set hhldtype4 = P010002",
                      "update %s set hhldtype5 = P010017",
                      "update %s set hhldrage1 = P012002",
                      "update %s set hhldrage2 = P012017",
                      "update %s set hhldfam1 = hhldtype1 + hhldtype2 + hhldtype3",
                      "update %s set hhldfam2 = hhldtype4 + hhldtype5",


                      "drop table hhld_marginals",
                      "drop table gq_marginals",
                      "drop table person_marginals",
                      """create table hhld_marginals select state, county, tract, bg, hhldinc1, hhldinc2, hhldinc3, hhldinc4, hhldinc5, hhldinc6, hhldinc7, hhldinc8,"""
                      """hhldsize1, hhldsize2, hhldsize3, hhldsize4, hhldsize5, hhldsize6, hhldsize7, hhldtype1, hhldtype2, hhldtype3, hhldtype4, hhldtype5,"""
                      """childpresence1, childpresence2, hhldrage1, hhldrage2, hhldfam1, hhldfam2 from %s""",
                      "create table gq_marginals select state, county, tract, bg, groupquarter1, groupquarter2 from %s",
                      """create table person_marginals select state, county, tract, bg, agep1, agep2, agep3, agep4, agep5, agep6, agep7, agep8, agep9, agep10,"""
                      """gender1, gender2, race1, race2, race3, race4, race5, race6, race7, employment1, employment2, employment3, employment4 from"""
                      """ %s"""]


                   

                   
 


